/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'

import { Route as RolesRouteImport } from './routes/roles'

import { Route as LoginRouteImport } from './routes/login'
import { Route as AllLettersRouteImport } from './routes/all-letters'
import { Route as R500RouteImport } from './routes/500'
import { Route as R404RouteImport } from './routes/404'
import { Route as R403RouteImport } from './routes/403'
import { Route as R401RouteImport } from './routes/401'
import { Route as IndexRouteImport } from './routes/index'


const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',

  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AllLettersRoute = AllLettersRouteImport.update({
  id: '/all-letters',
  path: '/all-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const R401Route = R401RouteImport.update({
  id: '/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/all-letters': typeof AllLettersRoute
  '/login': typeof LoginRoute

  '/roles': typeof RolesRoute

}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/all-letters': typeof AllLettersRoute
  '/login': typeof LoginRoute

  '/roles': typeof RolesRoute

}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/all-letters': typeof AllLettersRoute
  '/login': typeof LoginRoute

  '/roles': typeof RolesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/401' | '/403' | '/404' | '/500' | '/login' | '/roles'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/401' | '/403' | '/404' | '/500' | '/login' | '/roles'
  id: '__root__' | '/' | '/401' | '/403' | '/404' | '/500' | '/login' | '/roles'

  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R401Route: typeof R401Route
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  AllLettersRoute: typeof AllLettersRoute
  LoginRoute: typeof LoginRoute

  RolesRoute: typeof RolesRoute

}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {

    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport

      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-letters': {
      id: '/all-letters'
      path: '/all-letters'
      fullPath: '/all-letters'
      preLoaderRoute: typeof AllLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/401': {
      id: '/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof R401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R401Route: R401Route,
  R403Route: R403Route,
  R404Route: R404Route,
  R500Route: R500Route,
  AllLettersRoute: AllLettersRoute,
  LoginRoute: LoginRoute,

  RolesRoute: RolesRoute,

}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
